### PR TITLE
Version 1.73.0

### PR DESCRIPTION
**Pull request by WilliamDEdwards**
# Changes

Update to API version 1.145.

# Checks

- [x] The version constant is updated in `Client.php`
- [x] The changelog is updated (when applicable)
- [x] The supported Cluster API version is updated in the README (when applicable)

### CODE REVIEW

**Review by dvdheiden — APPROVED** [review]

**Comment by mbardelmeijer** [comment]
The `server_software_name` seems to be missing from the `VirtualHosts` -> `update` call. We ran into an issue on this version while updating the virtual host server_aliases:

```
{
"loc": [
"body",
"server_software_name"
],
"msg": "field required",
"type": "value_error.missing"
}
]
```

**Comment by dvdheiden** [comment]
Hi @mbardelmeijer! I will take a look at this later today.

**Comment by WilliamDEdwards** [comment]
@mbardelmeijer 

Fixed in 48463b4. The branch it is in will be merged to main ASAP.

**Comment by dvdheiden** [comment]
Fixed in [1.74.0](https://github.com/CyberfusionNL/cyberfusion-cluster-api-client/releases/tag/v1.74.0). 

If you encounter any issues, feel free to open [an issue](https://github.com/CyberfusionNL/cyberfusion-cluster-api-client/issues/new/choose) as comments on merged pull requests might be missed.

**Comment by mbardelmeijer** [comment]
@dvdheiden cheers! Makes sense, willdo next time! :)

**Pull request merged**
